/**
 * tenant.routes.js — Tenant management + domain verification
 *
 * Domain verification flow:
 *   1. POST /tenants/:id/domains/verify-init  → returns DNS TXT token
 *   2. Admin adds TXT record to their DNS
 *   3. POST /tenants/:id/domains/verify-confirm → checks DNS, marks verified
 *
 * Only verified domains are used for SSO auto-provisioning.
 * This prevents email-spoofing attacks (attacker@acme.com gaining acme.com tenant access).
 */
const express = require('express');
const dns     = require('dns').promises;
const Tenant  = require('../models/Tenant');
const User    = require('../models/User');
const { requireAuth, requireRole, normaliseRole } = require('../middleware/auth');

const router = express.Router();

// ─── GET /tenants — super_admin: all; others: own tenant ─────────────────────
router.get('/', requireAuth, async (req, res) => {
  try {
    const role = normaliseRole(req.authUser.role);
    if (role === 'super_admin') {
      const tenants = await Tenant.find({ isActive: true }).sort({ name: 1 }).lean();
      return res.json({ data: tenants });
    }
    if (!req.authUser.tenantId) return res.json({ data: [] });
    const tenant = await Tenant.findById(req.authUser.tenantId).lean();
    return res.json({ data: tenant ? [tenant] : [] });
  } catch (err) {
    res.status(500).json({ message: 'Server error' });
  }
});

// ─── POST /tenants — super_admin only ────────────────────────────────────────
router.post('/', requireAuth, requireRole('super_admin'), async (req, res) => {
  try {
    const { name } = req.body;
    if (!name?.trim()) return res.status(400).json({ message: 'name required' });

    const exists = await Tenant.findOne({ name: name.trim() });
    if (exists) return res.status(409).json({ message: 'Tenant name already exists' });

    const tenant = await Tenant.create({ name: name.trim(), createdBy: req.authUser._id });
    res.status(201).json({ message: 'Tenant created', data: tenant });
  } catch (err) {
    res.status(500).json({ message: 'Server error' });
  }
});

// ─── POST /tenants/:id/domains/verify-init ───────────────────────────────────
// Adds a domain entry with a DNS TXT token. Admin must publish this to DNS.
router.post('/:id/domains/verify-init', requireAuth, requireRole('super_admin'), async (req, res) => {
  try {
    const { domain } = req.body;
    if (!domain?.trim()) return res.status(400).json({ message: 'domain required' });

    const cleanDomain = domain.toLowerCase().trim();

    // Block public email providers
    const PUBLIC_DOMAINS = ['gmail.com','yahoo.com','outlook.com','hotmail.com','live.com','icloud.com','protonmail.com','aol.com'];
    if (PUBLIC_DOMAINS.includes(cleanDomain)) {
      return res.status(400).json({ message: `"${cleanDomain}" is a public email provider and cannot be used as a tenant domain.` });
    }

    const tenant = await Tenant.findById(req.params.id);
    if (!tenant) return res.status(404).json({ message: 'Tenant not found' });

    // Check if domain already registered to another tenant
    const conflict = await Tenant.findOne({
      _id: { $ne: tenant._id },
      'domains.domain': cleanDomain,
      'domains.isVerified': true,
    });
    if (conflict) {
      return res.status(409).json({ message: `Domain "${cleanDomain}" is already verified by another tenant.` });
    }

    // Remove existing unverified entry for this domain if present
    tenant.domains = tenant.domains.filter(d => d.domain !== cleanDomain);

    // Add new entry — dnsToken auto-generated by schema default
    tenant.domains.push({ domain: cleanDomain, isVerified: false });
    await tenant.save();

    const entry = tenant.domains.find(d => d.domain === cleanDomain);
    res.json({
      message:      'Domain verification initiated',
      domain:       cleanDomain,
      dnsToken:     entry.dnsToken,
      instructions: `Add a DNS TXT record to "${cleanDomain}" with value: "${entry.dnsToken}". Then call POST /tenants/${tenant._id}/domains/verify-confirm`,
    });
  } catch (err) {
    res.status(500).json({ message: 'Server error' });
  }
});

// ─── POST /tenants/:id/domains/verify-confirm ────────────────────────────────
// Checks DNS TXT record and marks domain as verified.
router.post('/:id/domains/verify-confirm', requireAuth, requireRole('super_admin'), async (req, res) => {
  try {
    const { domain } = req.body;
    if (!domain?.trim()) return res.status(400).json({ message: 'domain required' });

    const cleanDomain = domain.toLowerCase().trim();
    const tenant = await Tenant.findById(req.params.id);
    if (!tenant) return res.status(404).json({ message: 'Tenant not found' });

    const entry = tenant.domains.find(d => d.domain === cleanDomain);
    if (!entry) return res.status(404).json({ message: 'Domain not found. Call verify-init first.' });
    if (entry.isVerified) return res.json({ message: 'Domain already verified', domain: cleanDomain });

    // Check DNS TXT records
    let records = [];
    try {
      records = (await dns.resolveTxt(cleanDomain)).flat();
    } catch (dnsErr) {
      return res.status(400).json({ message: `DNS lookup failed for "${cleanDomain}": ${dnsErr.message}` });
    }

    if (!records.includes(entry.dnsToken)) {
      return res.status(400).json({
        message:  `DNS TXT record not found. Expected: "${entry.dnsToken}"`,
        found:    records,
        hint:     'DNS propagation can take up to 48 hours. Try again later.',
      });
    }

    // Mark verified
    await Tenant.findOneAndUpdate(
      { _id: tenant._id, 'domains.domain': cleanDomain },
      { $set: { 'domains.$.isVerified': true, 'domains.$.verifiedAt': new Date() } }
    );

    res.json({ message: `Domain "${cleanDomain}" verified successfully`, domain: cleanDomain });
  } catch (err) {
    res.status(500).json({ message: 'Server error' });
  }
});

// ─── POST /tenants/:id/assign-admin ──────────────────────────────────────────
router.post('/:id/assign-admin', requireAuth, requireRole('super_admin'), async (req, res) => {
  try {
    const { userId } = req.body;
    if (!userId) return res.status(400).json({ message: 'userId required' });

    const tenant = await Tenant.findById(req.params.id);
    if (!tenant) return res.status(404).json({ message: 'Tenant not found' });

    const existing = await User.findOne({ tenantId: tenant._id, role: 'company_admin', isDeleted: { $ne: true } });
    if (existing) {
      return res.status(409).json({ message: `Tenant already has a company_admin: "${existing.username}". Remove them first.` });
    }

    const user = await User.findOneAndUpdate(
      { _id: userId, isDeleted: { $ne: true } },
      { $set: { role: 'company_admin', tenantId: tenant._id }, $inc: { tokenVersion: 1 } },
      { new: true }
    );
    if (!user) return res.status(404).json({ message: 'User not found' });

    res.json({ message: `"${user.username}" is now company_admin of "${tenant.name}"`, data: { user: { _id: user._id, username: user.username, role: user.role }, tenant } });
  } catch (err) {
    res.status(500).json({ message: 'Server error' });
  }
});

module.exports = router;
